### ISSUE TITLE
'Permission denied' when trying to paste logs 

### ISSUE THREAD

**Issue by kutzi** [krzysztofslusarski/jvm-gc-logs-analyzer#25]
I got this in the webapp when trying to use 'Upload logs from clipboard'
```
2021-08-03 13:59:45.142 ERROR 18451 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.io.FileNotFoundException: /uploads8d3154d5-dcb9-4233-ab37-38f647e3f118plain-text.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method) ~[na:na]
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298) ~[na:na]
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[na:na]
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126) ~[na:na]
	at java.base/java.io.PrintWriter.<init>(PrintWriter.java:200) ~[na:na]
	at pl.ks.profiling.io.StorageUtils.savePlainText(StorageUtils.java:49) ~[io-utils-1.1-SNAPSHOT.jar!/:1.1-SNAPSHOT]
	at pl.ks.profiling.safepoint.analyzer.web.StatsController.enqueue(StatsController.java:96) ~[classes!/:1.1-SNAPSHOT]
```

**Comment by kutzi** [comment]
Seems that it's trying to access a global directory (/uploads...) instead of a one relative to the app location

**Comment by krzysztofslusarski** [comment]
fixed at master

**Comment by kutzi** [comment]
Works!
