### ISSUE TITLE
JVM 17 G1: NumberFormatException

### ISSUE THREAD

**Issue by yanns** [krzysztofslusarski/jvm-gc-logs-analyzer#27]
When parsing GC logs from JVM 17 using G1, I got the following exception:
```
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "16777232 @ 0x0000000600000000) remset 0 code roots 0 marked 0 reclaim candidate 1 type array 1"
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at pl.ks.profiling.safepoint.analyzer.standalone.AnalyzerStandaloneApplication.lambda$onWorkerComplete$4(AnalyzerStandaloneApplication.java:346)
```

I have started the application with the GC log parameters as defined in https://github.com/krzysztofslusarski/jvm-gc-logs-analyzer#jvm-xlog-configuration

**Comment by krzysztofslusarski** [comment]
Can you share the log file?

**Comment by yanns** [comment]
Not really.
I've found some lines containing the string:
```
[2021-12-30T09:48:35.022+0000][75.406s][debug][gc,humongous         ] GC(18) Humongous region 0 (object size 16777232 @ 0x0000000600000000) remset 0 code roots 0 marked 0 reclaim candidate 1 type array 1
[2021-12-30T09:48:35.229+0000][75.613s][debug][gc,humongous         ] GC(20) Humongous region 0 (object size 16777232 @ 0x0000000600000000) remset 0 code roots 0 marked 0 reclaim candidate 1 type array 1
```

Does it hlep?

**Comment by krzysztofslusarski** [comment]
I fixed the Exception, you can check the master branch

**Comment by yanns** [comment]
Thanks a lot!

I've tried to use the master branch, but the compilation is failing with javac 17:
```
$ jvm-gc-logs-analyzer git:(master) javac -version
javac 17.0.1
$ jvm-gc-logs-analyzer git:(master) mvn clean package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] jvm-gc-logs-analyzer                                               [pom]
[INFO] io-utils                                                           [jar]
[INFO] gui-commons                                                        [jar]
[INFO] safepoint-analyzer-commons                                         [jar]
[INFO] safepoint-analyzer-standalone                                      [jar]
[INFO] web-commons                                                        [jar]
[INFO] safepoint-analyzer-web                                             [jar]
[INFO]
[INFO] ----------------< pl.ks.profiling:jvm-gc-logs-analyzer >----------------
[INFO] Building jvm-gc-logs-analyzer 1.2-SNAPSHOT                         [1/7]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ jvm-gc-logs-analyzer ---
[INFO]
[INFO] --- gmavenplus-plugin:1.6.2:generateStubs (default) @ jvm-gc-logs-analyzer ---
[INFO] No sources specified for stub generation.  Skipping.
[INFO] Generated 0 stubs.
[INFO]
[INFO] --- gmavenplus-plugin:1.6.2:compile (default) @ jvm-gc-logs-analyzer ---
[INFO] No sources specified for compilation.  Skipping.
[INFO]
[INFO] --- gmavenplus-plugin:1.6.2:compileTests (default) @ jvm-gc-logs-analyzer ---
[INFO] No sources specified for compilation.  Skipping.
[INFO]
[INFO] --- build-helper-maven-plugin:3.2.0:add-test-source (add-groovy-test-source) @ jvm-gc-logs-analyzer ---
[INFO] Test Source directory: /Users/yannsimon/projects/jvm-gc-logs-analyzer/src/test/groovy added.
[INFO] Test Source directory: /Users/yannsimon/projects/jvm-gc-logs-analyzer/src/test/java added.
[INFO]
[INFO] ----------------------< pl.ks.profiling:io-utils >----------------------
[INFO] Building io-utils 1.2-SNAPSHOT                                     [2/7]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ io-utils ---
[INFO] Deleting /Users/yannsimon/projects/jvm-gc-logs-analyzer/io-utils/target
[INFO]
[INFO] --- gmavenplus-plugin:1.6.2:generateStubs (default) @ io-utils ---
[INFO] No sources specified for stub generation.  Skipping.
[INFO] Generated 0 stubs.
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ io-utils ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /Users/yannsimon/projects/jvm-gc-logs-analyzer/io-utils/src/main/resources
[INFO] skip non existing resourceDirectory /Users/yannsimon/projects/jvm-gc-logs-analyzer/io-utils/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ io-utils ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 16 source files to /Users/yannsimon/projects/jvm-gc-logs-analyzer/io-utils/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for jvm-gc-logs-analyzer 1.2-SNAPSHOT:
[INFO]
[INFO] jvm-gc-logs-analyzer ............................... SUCCESS [  0.444 s]
[INFO] io-utils ........................................... FAILURE [  0.906 s]
[INFO] gui-commons ........................................ SKIPPED
[INFO] safepoint-analyzer-commons ......................... SKIPPED
[INFO] safepoint-analyzer-standalone ...................... SKIPPED
[INFO] web-commons ........................................ SKIPPED
[INFO] safepoint-analyzer-web ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.548 s
[INFO] Finished at: 2022-01-03T13:59:25+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project io-utils: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x1f4f0fcc) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x1f4f0fcc -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
```

**Comment by krzysztofslusarski** [comment]
You need to compile with JDK 11, it is mentioned in README

**Comment by yanns** [comment]
> You need to compile with JDK 11, it is mentioned in README

I saw that, but it's very old. It's not so easy to install a old JVM version just for one project.

**Comment by krzysztofslusarski** [comment]
You don't need to install JDK. It is good enough to download and unpack one, and run ```JAVA_HOME=/Path/to/jdk mvn clean package```. It is completly normal to have several JDKs. I have over 10 on my machine.
