### ISSUE TITLE
ZGC support

### ISSUE THREAD

**Issue by sureshg** [krzysztofslusarski/jvm-gc-logs-analyzer#29]
Opening ZGC logs throws the following error

```
Caused by: java.lang.IllegalStateException: No match found
	at java.base/java.util.regex.Matcher.group(Matcher.java:644)
	at java.base/java.util.regex.Matcher.group(Matcher.java:603)
	at pl.ks.profiling.safepoint.analyzer.commons.shared.gc.parser.GCUnifiedLogFileParser.addSizesAndTime(GCUnifiedLogFileParser.java:166)
	at pl.ks.profiling.safepoint.analyzer.commons.shared.gc.parser.GCUnifiedLogFileParser$GcLineParser.apply(GCUnifiedLogFileParser.java:51)
	at pl.ks.profiling.safepoint.analyzer.commons.shared.gc.parser.GCUnifiedLogFileParser.useFirstAccepting(GCUnifiedLogFileParser.java:113)
	at pl.ks.profiling.safepoint.analyzer.commons.shared.gc.parser.GCUnifiedLogFileParser.parseLine(GCUnifiedLogFileParser.java:102)
	at pl.ks.profiling.safepoint.analyzer.commons.shared.StatsService.createAllStatsUnifiedLogger(StatsService.java:157)
	... 8 more
```

**Comment by sureshg** [comment]
Nm..just saw this PR after creating the issue - https://github.com/krzysztofslusarski/jvm-gc-logs-analyzer/pull/26

**Comment by krzysztofslusarski** [comment]
Hi, there is no support for Shenandoah/ZGC yet. The logs of ZGC are completly different (in terms of parsing) then G1, I need to create seperate parsers for them. I want to do it soon, but cannot promise any deadline.

**Comment by krzysztofslusarski** [comment]
Some basic parser was committed today.
